export const State = Object.freeze({
  INACTIVE: 'INACTIVE',
  ACTIVE: 'ACTIVE',
  ACTIVE_SYNCHRONIZE: 'ACTIVE_SYNCHRONIZE',
  ACTIVE_SEPARATION: 'ACTIVE_SEPARATION',
  ACTIVE_COLLECTING: 'ACTIVE_COLLECTING',
  ACTIVE_MEASURE: 'ACTIVE_MEASURE'
});
